from 데이터 import Stack

stack = Stack(5)
print(stack.arr)
stack.push(1)
print(stack.arr)
stack.push(1)
print(stack.arr)
stack.push(1)
print(stack.arr)
stack.push(1)
print(stack.arr)
stack.push(1)
print(stack.arr)
stack.push(1)

stack.pop()
print(stack.arr)
stack.pop()
print(stack.arr)
stack.pop()
print(stack.arr)
stack.pop()
print(stack.arr)
stack.pop()
print(stack.arr)
stack.pop()